<a href="https://colab.research.google.com/github/ftimahhy-cloud/pds_yy1/blob/main/LatihanPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#LOAD DATA dari link
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv')
df

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,Kota Sorong,2020,116.28,67.28,73.72,156.21,142.40,94.42,141.83,174.79,...,146.82,114.70,132.38,143.36,54.51,13.70,9.22,0.39,78.66,3.45
1063,Kota Sorong,2021,138.49,113.67,57.69,173.31,83.56,99.41,91.17,248.49,...,214.92,129.11,160.15,145.88,189.26,7.77,3.27,0.31,80.79,4.39
1064,Kota Sorong,2022,105.81,108.63,41.69,232.20,125.93,92.21,130.82,274.78,...,160.51,71.74,264.24,259.16,246.84,11.44,9.03,0.33,66.97,2.12
1065,Kota Sorong,2023,80.40,49.05,63.66,137.98,94.78,101.75,126.07,265.28,...,212.06,125.80,221.05,212.70,185.33,16.30,9.80,0.46,84.08,6.63
1066,Kota Sorong,2024,94.64,79.05,72.16,206.04,111.61,138.26,169.47,181.43,...,65.36,291.64,270.61,203.54,130.97,16.54,8.06,0.49,83.27,3.03

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.tail(5)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
1062,Kota Sorong,2020,116.28,67.28,73.72,156.21,142.40,94.42,141.83,174.79,...,146.82,114.70,132.38,143.36,54.51,13.70,9.22,0.39,78.66,3.45
1063,Kota Sorong,2021,138.49,113.67,57.69,173.31,83.56,99.41,91.17,248.49,...,214.92,129.11,160.15,145.88,189.26,7.77,3.27,0.31,80.79,4.39
1064,Kota Sorong,2022,105.81,108.63,41.69,232.20,125.93,92.21,130.82,274.78,...,160.51,71.74,264.24,259.16,246.84,11.44,9.03,0.33,66.97,2.12
1065,Kota Sorong,2023,80.40,49.05,63.66,137.98,94.78,101.75,126.07,265.28,...,212.06,125.80,221.05,212.70,185.33,16.30,9.80,0.46,84.08,6.63
1066,Kota Sorong,2024,94.64,79.05,72.16,206.04,111.61,138.26,169.47,181.43,...,65.36,291.64,270.61,203.54,130.97,16.54,8.06,0.49,83.27,3.03

Warning: Total number of columns (24) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.head()

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Kota                    1067 non-null   object
 1   Tahun                   1067 non-null   int64
 2   DBH_PAJAK               1067 non-null   float64
 3   DBH_SDA                 1067 non-null   float64
 4   DBH_Lainnya             1067 non-null   float64
 5   DAU_Grant               1067 non-null   float64
 6   DAU_Earmark             1067 non-null   float64
 7   DAK_Fisik               1067 non-null   float64
 8   DAK_Nonfisik            1067 non-null   float64
 9   PAD                     1067 non-null   float64
 10  ICT                     1067 non-null   float64
 11  bm_pendidikan           1067 non-null   float64
 12  bm_kesehatan            1067 non-null   float64
 13  bm_perumahan            1067 non-null   float64
 14  bm_lingkungan           1067 non-null   float64
 15  bm_ekonomi              1067 non-null   float64
 16  bm_infrastruktur        1067 non-null   float64
 17  bm_pariwisata           1067 non-null   float64
 18  bm_perlindungan_sosial  1067 non-null   float64
 19  KEMISKINAN              1067 non-null   float64
 20  PENGANGGURAN            1067 non-null   float64
 21  KETIMPANGAN             1067 non-null   float64
 22  IPM                     1067 non-null   float64
 23  PE                      1067 non-null   float64
dtypes: float64(22), int64(1), object(1)
memory usage: 200.2+ KB

In [ ]:
df.describe()

,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,ICT,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
count,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,...,1067.000000,1067.00000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2019.000000,107.905464,71.138960,53.830628,178.029850,107.452034,107.783393,106.766401,215.204077,81.898013,...,172.587882,173.69358,174.611565,172.471546,171.014255,12.538519,6.466692,0.398641,72.378847,4.958547
std,3.163761,57.856235,42.449883,28.680751,87.999498,54.994876,56.152152,56.852234,110.345873,11.873095,...,71.441473,72.10115,72.044194,71.984621,71.837922,4.258490,2.033596,0.057334,7.211382,1.668266
min,2014.000000,11.550000,5.940000,6.190000,22.330000,12.260000,12.710000,13.420000,24.060000,60.630000,...,50.010000,50.06000,50.980000,50.060000,50.060000,5.000000,3.000000,0.300000,60.010000,2.000000
25%,2016.000000,69.770000,42.840000,34.390000,118.675000,69.420000,68.740000,65.130000,138.570000,71.000000,...,109.455000,111.02500,111.405000,110.245000,108.400000,9.055000,4.750000,0.350000,66.075000,3.590000
50%,2019.000000,96.720000,61.830000,47.760000,163.550000,98.520000,99.410000,95.910000,198.420000,82.030000,...,171.960000,170.87000,174.580000,170.560000,168.840000,12.470000,6.390000,0.400000,72.420000,4.960000
75%,2022.000000,137.460000,90.070000,68.720000,223.535000,137.480000,134.720000,135.945000,273.040000,92.340000,...,232.870000,237.29000,235.460000,236.230000,231.505000,16.140000,8.235000,0.450000,78.765000,6.345000
max,2024.000000,365.020000,278.510000,166.720000,582.960000,303.090000,353.440000,381.840000,686.780000,100.000000,...,299.890000,299.70000,299.870000,299.800000,299.360000,19.990000,10.000000,0.500000,84.950000,7.990000

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
indeks_tertinggi = df['PAD'].idxmax()
row_tertinggi = df.loc[indeks_tertinggi]

nilai_tertinggi = row_tertinggi['PAD']
tahun_tertinggi = row_tertinggi['Tahun']

print("Tahun dengan nilai PAD tertinggi adalah : " , int(tahun_tertinggi) , (nilai_tertinggi))
print("Berikut adalah detail row tersebut: " , row_tertinggi)

Tahun dengan nilai PAD tertinggi adalah :  2021 686.78
Berikut adalah detail row tersebut:  Kota                      Kota Tarakan
Tahun                             2021
DBH_PAJAK                       310.26
DBH_SDA                         237.35
DBH_Lainnya                     166.72
DAU_Grant                       413.94
DAU_Earmark                     269.95
DAK_Fisik                       308.14
DAK_Nonfisik                    292.04
PAD                             686.78
ICT                              94.46
bm_pendidikan                   284.77
bm_kesehatan                     270.6
bm_perumahan                    139.22
bm_lingkungan                   176.48
bm_ekonomi                      120.64
bm_infrastruktur                235.66
bm_pariwisata                   267.83
bm_perlindungan_sosial           156.1
KEMISKINAN                        5.21
PENGANGGURAN                      5.49
KETIMPANGAN                       0.36
IPM                              66.56
PE                                4.13
Name: 1052, dtype: object